version: "3.9"
services:
  webserver:
    image: nginx:latest
    volumes: 
      - ./front-end:/usr/share/nginx/html
      - ./front-end/nginx/certs:/etc/nginx/certs
      - ./front-end/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"